#pragma once

#ifndef GRAPHICS_SETTINGS_NUMFRAMERESOURCES
#define GRAPHICS_SETTINGS_NUMFRAMERESOURCES 3u
#endif

#ifndef GRAPHICS_BACKBUFFER_DEFAULT_CLEAR_COLOUR
#define GRAPHICS_BACKBUFFER_DEFAULT_CLEAR_COLOUR float4(0.1f, 0.1f, 0.1f, 1.f)
#endif

#ifndef GRAPHICS_FRAMEBUFFER_DEFAULT_CLEAR_COLOUR
#define GRAPHICS_FRAMEBUFFER_DEFAULT_CLEAR_COLOUR float4(0.690196097f, 0.768627524f, 0.870588303f, 1.f)
#endif

#ifndef GRAPHICS_DEPTH_DEFAULT_CLEAR_COLOUR
#define GRAPHICS_DEPTH_DEFAULT_CLEAR_COLOUR 0.f
#endif

#ifndef GRAPHICS_STENCIL_DEFAULT_CLEAR_COLOUR
#define GRAPHICS_STENCIL_DEFAULT_CLEAR_COLOUR 0u
#endif

